test

diff --git a/home/dot_bashrc b/home/dot_bashrc
--- a/home/dot_bashrc
+++ b/home/dot_bashrc
@@ -154,6 +154,81 @@ alias d='dirs -v'
 for index in {1..9}; do alias "$index"="pushd +${index}";unset index; done
 
 for f in ~/.config/.rc/sh_*.sh; do  source "$f"; done
-for f in ~/.config/.rc/bash_*.sh; do  source "$f"; done
 # [ -f ~/.config/.rc/shlast_*.sh ] && for f in ~/.config/.rc/shlast_*.sh; do  source "$f"; done || echo
 for f in ~/.config/.rc/shlast_*.sh; do  source "$f"; done
+
+#######################################################
+# Prompt
+#######################################################
+# https://en.wikipedia.org/wiki/ANSI_escape_code#Colors
+# https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
+# https://misc.flogisoft.com/bash/tip_colors_and_formatting
+# https://linuxcommand.org/lc3_adv_tput.php
+
+# tput setaf <value>	Set foreground color    setab <value>	Set background color
+# 0 sgr0 reset all
+# 1 bold  21 reset
+# 2 Dim   22 reset                    '\[\e[2m\]' # "\001$(tput dim)\002"
+# 4 smu   24 rmul reset  Underlined
+# 5 blink 25 reset
+# 7 rev   27 reset  Reverse
+# 7 smso	Start “standout” mode   27 rmso	End “standout” mode
+# 8 invis  28 reset   Hidden
+# echo "$(tput bold); $(tput setaf 2)" | \cat -v # cat -v: Displays non-printing characters
+# tput: Portable, readable, but slower (it runs a binary).Escape : Fast, direct, but hard-coded and less portable.
+
+#          setaf       setab                bold (with 0-7)      bold (with 0-7)
+# Color    Normal(FG)  Background  Color    Bright(FG)           Bright Back.
+# Black    \e[0;30m 0    \e[0;40m      DarkGray \e[1;30m \e[90m 8    \e[1;40m \e[100m
+# Red      \e[0;31m 1    \e[0;41m      LRed     \e[1;31m \e[91m 9    \e[1;41m \e[101m
+# Green    \e[0;32m 2    \e[0;42m      LGreen   \e[1;32m \e[92m 10   \e[1;42m \e[102m
+# Brown    \e[0;33m 3    \e[0;43m      Yellow   \e[1;33m \e[93m 11   \e[1;43m \e[103m
+# Blue     \e[0;34m 4    \e[0;44m      LBlue    \e[1;34m \e[94m 12   \e[1;44m \e[104m
+# Magenta  \e[0;35m 5    \e[0;45m      LMagenta \e[1;35m \e[95m 13   \e[1;45m \e[105m
+# Cyan     \e[0;36m 6    \e[0;46m      LCyan    \e[1;36m \e[96m 14   \e[1;46m \e[106m
+# White    \e[0;37m 7    \e[0;47m      LGray    \e[1;37m \e[97m 15   \e[1;47m \e[107m
+# Default  \e[0;39m      \e[0;49m
+# gray='\[\e[1;30m\]'  # "\[$(tput setaf 8)\]" "\001$(tput bold)$(tput setaf 0)\002"
+
+# \e = \033 = \x1B  $escape char  # \[ = \001 Start of Heading (SOH)  # \] = \002 Start of Text (STX)
+# none print char has to be between \[ \] (\001 \002) to they dont count as char to calc prompt length
+
+# og_setprompt=1
+# og_setprompt=$1
+
+case "$og_setprompt" in
+   1)
+        reset='\[\e[0m\]' # no color  # "\001$(tput sgr0)\002"
+        BRACKET_COLOR="\[\e[1;32m\]"  # "\[\033[38;5;35m\]" lgreen
+        CLOCK_COLOR="$BRACKET_COLOR"
+        JOB_COLOR='\[\e[1;34m\]'   # "\[\033[38;5;33m\]"  lblue
+        PATH_COLOR='\[\e[1;34m\]'  # "\[\033[38;5;33m\]"  lblue
+        LINE_COLOR='\[\e[0;37m\]' # "\[\033[38;5;248m\]"  lgray
+
+        LINE_STRAIGHT="$LINE_COLOR\342\[\224\200\]"        # ─
+        LINE_BOTTOM_CORNER="\n$LINE_COLOR\342\[\224\224\]$LINE_STRAIGHT$LINE_STRAIGHT"   # └──
+        LINE_UPPER_CORNER="$LINE_COLOR\342\[\224\214\]$LINE_STRAIGHT"      # ┌───
+        ERROR_CHAR="\342\[\234\227\]"   # ✗
+
+        P_ERROR="\$([[ \$? != 0 ]] && echo \"\[\e[0;31m\][$ERROR_CHAR]\")$(if [[ ${EUID} == 0 ]]; then echo '\[\e[1;31m\]'; else echo '\[\e[0;37m\]'; fi)"
+        P_CLOCK="$BRACKET_COLOR[$CLOCK_COLOR\t$BRACKET_COLOR]$LINE_STRAIGHT"
+        P_PATH="$BRACKET_COLOR$PATH_COLOR \w"
+        P_JOB="$BRACKET_COLOR[$JOB_COLOR\j$BRACKET_COLOR]$LINE_STRAIGHT"
+
+        # jays prompt  256 color format
+        P_HOST="$BRACKET_COLOR[\H:]"
+        END_CHARACTER="|" #    "🦄" mess is up
+
+        # P_HOST="\[\e[0;31m\][\u\[\e[1;33m\]@\[\e[0;36m\]\h\[\e[0;31m\]]"  #red yellow lcyan
+        # P_PATH="$LINE_STRAIGHT\[\e[0;32m\][\w]"  # green
+        # END_CHARACTER="$C3$reset\[\e[1;33m\] \$"
+        # P_CLOCK=""
+        # P_JOB=""
+
+        tty -s && export PS1="$LINE_UPPER_CORNER$P_ERROR$LINE_STRAIGHT$P_CLOCK$P_JOB$P_HOST$P_PATH$LINE_BOTTOM_CORNER$END_CHARACTER${reset} "
+        # https://www.learnlinux.tv/10-linux-terminal-tips-and-tricks-to-enhance-your-workflow/
+     ;;
+   2)
+      export PS1="\[\e[2m\][\t] \[\e[0;32m\]\u@\h$\[\e[0;33m\]\w\\[\e[0m\]" # dim [hh:mm:ss] user@host workingdir$ green brown reset
+   ;;
+esac
